# A simple scene with a box

material mat1 { 0.7 1.0 0.7 } { 0.5 0.7 0.5 } 25

box : b1 { -125 -150 0 } 100
surfaceproperty :b1 mat1
rotate :b1 y -15

point_light { -100.0 150.0 400.0 } { 0.9 0.9 0.9 } none
point_light { 4.0 -1.0 1.50 } { 0.7 0.0 0.7 }  none
ambient_light { 0.3 0.3 0.3 }

render : size { 200 200 } eyepoint { 0 0 400 } fov 50 viewdirection { 0 0 -1 } updirection { 0 1 0 } file simple.png
exit
